### ISSUE TITLE
Parser doesn't support polybeziers or absolute commands

### ISSUE THREAD

**Issue by personalnadir** [singularity-is-i/SVG-Path-in-Lua#2]
The existing code assumes that the moveto command is followed by only one curveto command and that they are both represented using the lowercase 'm' and 'c' commands. It's pretty easy to hack support for absolute points ('M' and 'C') and polybeziers in, but I've not yet found a neat way of doing it. 

If I've got time, | may fix this myself, but I figured I'd raise an issue for now in case anyone gets stuck like I did.

**Comment by braneof** [comment]
I fixed a bug with the bezier path code in my fork of this repo, it might solve part of your issue. My fork: https://github.com/braneof/SVG-Path-in-Lua
